#!/usr/bin/env bash

export MIMESIS_ROOT="${MIMESIS_ROOT:-$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)}"
export MIMESIS_MODEL_DIR="${MIMESIS_MODEL_DIR:-$MIMESIS_ROOT/models}"
export MIMESIS_DATA_DIR="${MIMESIS_DATA_DIR:-$MIMESIS_ROOT/data}"
export MIMESIS_OUTPUT_DIR="${MIMESIS_OUTPUT_DIR:-$MIMESIS_ROOT/outputs}"

export OPENAI_MODEL_NAME="${OPENAI_MODEL_NAME:-gpt-5-5}"
export JUDGE_MODEL_NAME="${JUDGE_MODEL_NAME:-$OPENAI_MODEL_NAME}"

mkdir -p "$MIMESIS_OUTPUT_DIR"
export HF_HOME="${HF_HOME:-$MIMESIS_OUTPUT_DIR/hf_cache}"
export WANDB_DIR="${WANDB_DIR:-$MIMESIS_OUTPUT_DIR/wandb}"
